#!/bin/bash
# Reads OPENROUTER_API_KEY from .env at the repo root and writes
# App/Generated/DevAPIKey.swift. The generated literal is wrapped in
# `#if DEBUG`, so Release binaries never contain the dev key.
#
# Run automatically as a pre-build script (project.yml). Safe to run
# by hand: `Tools/generate-dev-key.sh`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
OUT_DIR="${REPO_ROOT}/App/Generated"
OUT_FILE="${OUT_DIR}/DevAPIKey.swift"

mkdir -p "${OUT_DIR}"

RAW_KEY=""
if [ -f "${ENV_FILE}" ]; then
    RAW_KEY="$(awk -F= '/^[[:space:]]*OPENROUTER_API_KEY[[:space:]]*=/{ sub(/^[^=]*=[[:space:]]*/, ""); print; exit }' "${ENV_FILE}" || true)"
    RAW_KEY="${RAW_KEY%$'\r'}"
    RAW_KEY="${RAW_KEY#\"}"; RAW_KEY="${RAW_KEY%\"}"
    RAW_KEY="${RAW_KEY#\'}"; RAW_KEY="${RAW_KEY%\'}"
fi

# Validate: empty or obviously placeholder values produce a nil stub.
case "${RAW_KEY}" in
    ""|"sk-or-..."|"your-key-here"|"YOUR_KEY_HERE")
        VALUE_EXPR="nil"
        STATUS="not configured (BYOK fallback in Debug)"
        ;;
    *)
        # Allow only printable, non-whitespace characters to avoid Swift
        # literal breakage. OpenRouter keys are alphanumeric + dashes.
        if [[ ! "${RAW_KEY}" =~ ^[A-Za-z0-9._\-]+$ ]]; then
            echo "warning: OPENROUTER_API_KEY in .env contains unexpected characters; emitting nil." >&2
            VALUE_EXPR="nil"
            STATUS="invalid characters (BYOK fallback in Debug)"
        else
            VALUE_EXPR="\"${RAW_KEY}\""
            STATUS="bundled (${#RAW_KEY} chars)"
        fi
        ;;
esac

cat > "${OUT_FILE}" <<EOF
// Auto-generated by Tools/generate-dev-key.sh — do not edit, do not commit.
//
// The literal below is wrapped in #if DEBUG, so the Release binary never
// contains the bundled key. Release builds always require BYOK.

import Foundation

enum DevAPIKey {
    static let bundled: String? = {
        #if DEBUG
        return ${VALUE_EXPR}
        #else
        return nil
        #endif
    }()
}
EOF

echo "generate-dev-key: ${STATUS} -> ${OUT_FILE}"
